import type { Metadata } from "next";
import "./globals.css";

import { LocalModal } from "@/components/pagesinfo/local";
import { Butterfly_Kids } from "next/font/google";
import { HaruoModal } from "@/components/pagesinfo/haruo";
import { LanaModal } from "@/components/pagesinfo/lana";
import { MusicModal } from "@/components/pagesinfo/musics";

const butterfly_kids = Butterfly_Kids({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${butterfly_kids.className} antialiased`}>
        <LocalModal />
        <HaruoModal />
        <LanaModal />
        <MusicModal />
        {children}
      </body>
    </html>
  );
}
